### ISSUE TITLE
Assistance need

### ISSUE THREAD

**Issue by kwpugh** [Lemonszz/SetEffect#1]
I'm doing something wrong, but not sure what.

I created a craft weaker scripts to add an effect to the steel armor from Construct's Armory.

{
val steel_set = mods.SetEffect.newSet()
               .setName("steel_set")
               .withHead(<conarm:helmet>)
               .withChest(<conarm:chestplate>)
               .withLegs(<conarm:leggings>)
               .withFeet(<conarm:boots>)
               .addEffect(<potion:minecraft:resistance>.makePotionEffect(100, 1));

mods.SetEffect.register(steel_set);
}

Game loads up fine.   When I try to equip the last piece of armor the client hangs.   I have to forcibly close the client.

Here is the crash report after closure: https://gist.github.com/kwpugh/f3057fce1a151ac4b49ebd2f17131b62

Any guidance would be greatly appreciated.

**Comment by Lemonszz** [comment]
Thanks for the crash report. While this isn't actually a bug, it shouldn't crash like this.

I managed to get this working (http://lemons.party/i/z6la4.png)

There's a few things wrong with your script, You're missing the [bracket handler](https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Brackets/Bracket_Item) (<>) on your item and [potion](https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Brackets/Bracket_Potion). 

EG: 
`<minecraft:apple>`   
`<conarm:helmet>`   
`<potion:minecraft:resistance>`   

I've fixed up your script for you, let me know if you have further issues.

```
val steel_set =  mods.SetEffect.newSet()
.setName("steel_set")
.withHead(<conarm:helmet>)
.withChest(<conarm:chestplate>)
.withLegs(<conarm:leggings>)
.withFeet(<conarm:boots>)
.addEffect(<potion:minecraft:resistance>.makePotionEffect(100, 1));

mods.SetEffect.register(steel_set);
```

**Comment by kwpugh** [comment]
Thank you.
